### ISSUE TITLE
[FIXED]: Internet disconnection after 5-10 mins

### ISSUE THREAD

**Issue by lazerwolf22** [derekhe/msfs2020-google-map#114]
RESOLVED:

The issue was the addition of Pi-hole query rate-limiting by default with a recent update. The rate limit is set to allow no more than 1000 queries per 60 seconds. The limit us quickly reached using this mod. If you use a Pi-hole, to resolve it you need to edit /etc/pihole/pihole-FTL.conf and add the line RATE_LIMIT=0/0 or if already present change the values to 0/0. This fixes the issue in this case.
 

Thank you for your work!

BEFORE SUBMIT A BUG, PLEASE READ THE FAQ PAGE HERE: https://github.com/derekhe/msfs2020-google-map/wiki/FAQ

**Describe the bug**
Everything works great for 5 - 10 minutes the breaks my connection to the internet. All other PC's connected to the network still function normally but not mine. To restore internet I have to "ipconfig /flushdns" and unplug my network cable then plug it back in.

**To Reproduce**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 11
 - MOD Version [e.g. 22]  2021-11-20
 - MSFS Version, MS Store or Stream: Store

**Additional context**

**Comment by ziher123** [comment]
Try disabling IPv6, worked for me.

**Comment by lazerwolf22** [comment]
I was about to say "I never have that enabled!" But uhh... somehow it was enabled :)
Thanks for the tip!

**Comment by lazerwolf22** [comment]
Here is a log to review
[log.txt](https://github.com/derekhe/msfs2020-google-map/files/7579803/log.txt)

**Comment by derekhe** [comment]
Can you open maps.google.com without issue?
I see from the log that there are issue when accessing google.

**Comment by derekhe** [comment]
@lazerwolf22 fixed?

**Comment by lazerwolf22** [comment]
Google Maps always works fine. Mod still broken.

**Comment by ferryvanaesch** [comment]
[Errno 11001] getaddrinfo failed over and over again.

That looks like your DNS server is throttling you....

**Comment by tarukuu** [comment]
I am having the same problem.
I thought it was a non-mod issue, such as clean install of windows, reinstalling MSFS and XBOX.
Mr/Mis ferryvanaesch's advice was a great tip.
----error log
2021/11/25 08:05:12 [error] 1660#6704: *4687 connect() failed (10060: A connection attempt failed because the connected party did not properly 10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because the connected host has failed to respond) while connecting to upstream, client: 127 .0.0.1, server: khstorelive.azureedge.net, request: "GET /results/v1.21.0/vegetation_cgl/vgm120202.cgl?version=5 HTTP/1.1", upstream: " https://104.212.68.136:443/results/v1.21.0/vegetation_cgl/vgm120202.cgl?version=5", host: "khstorelive.azureedge.net"
-----
My provider is still preparing for IPv6, so I'm connecting via IPv4.
I have tried DNS 8.8.8.8 and am getting the same error.
I think this mod is great, but it seems to be difficult in my connection environment.

**Comment by ferryvanaesch** [comment]
Yes, your connection issue looks different: time-outs. That's not your DNS indeed. Frankly that could be anywhere, from your own pc to your router, your ISP or even the peering contracts they have. Without some in-depth analysis I can't tell you where the issue lies. 

Oh, it's Mr. ;-)

**Comment by derekhe** [comment]
Please try latest version: https://github.com/derekhe/msfs2020-google-map/releases/tag/2.3.2

**Comment by tarukuu** [comment]
Thank you.It is unclear to me what is going on, so I am attaching the LOG.The location is Kitakyushu, Fukuoka, Japan.No mods are installed. I'm glad if it's helpful. Windows の メール から送信 差出人: hesicong送信日時: 2021年11月28日 17:13宛先: derekhe/msfs2020-google-mapCC: tarukuu; Comment件名: Re: [derekhe/msfs2020-google-map] [BUG] Internet disconnection after 5-10 mins (Issue #114) Please try latest version: https://github.com/derekhe/msfs2020-google-map/releases/tag/2.3.2—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by derekhe** [comment]
Sorry, if you sending from the phone, I can't see the attachment. Please post it here.

**Comment by tarukuu** [comment]
OK Again  Windows の メール から送信 差出人: hesicong送信日時: 2021年11月29日 19:06宛先: derekhe/msfs2020-google-mapCC: tarukuu; Comment件名: Re: [derekhe/msfs2020-google-map] [BUG] Internet disconnection after 5-10 mins (Issue #114) Sorry, if you sending from the phone, I can't see the attachment. Please post it here.—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by derekhe** [comment]
Sorry, I still can't the posts, you had to put your attachment into https://github.com/derekhe/msfs2020-google-map/issues/114

**Comment by tarukuu** [comment]
https://drive.google.com/drive/folders/10GBcP5pk8XEVVgSz01qEdxKvSbtC8vJx?usp=sharing

its Error Log files

**Comment by tarukuu** [comment]
new virsion  2.3.3 log here
https://drive.google.com/drive/folders/10TFsIheGRBFdI6I7an4DFkRpBu6riVmt?usp=sharing

I think it is being replaced by Google maps. However, there is a delay in reading. It went offline due to the fact that it has a narrow bandwidth in a hair-trigger way.

AMD Ryzen 9 5900X
RTX 3070Ti
Memory 32GB
Internet connection speed 63.99 Mbps


--exsample--
2021/12/02 14:50:04 [error] 34796#17056: *1831 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while reading response header from upstream, client: 127.0.0.1, server: kh.ssl.ak.tiles.virtualearth.net, request: "GET /tiles/akh3112231302310113.jpeg?n=z&g=9591 HTTP/1.1", upstream: "http://127.0.0.1:39871/tiles/akh3112231302310113.jpeg?n=z&g=9591", host: "kh.ssl.ak.tiles.virtualearth.net"
2021/12/02 14:50:04 [warn] 34796#17056: *1831 upstream server temporarily disabled while reading response header from upstream, client: 127.0.0.1, server: kh.ssl.ak.tiles.virtualearth.net, request: "GET /tiles/akh3112231302310113.jpeg?n=z&g=9591 HTTP/1.1", upstream: "http://127.0.0.1:39871/tiles/akh3112231302310113.jpeg?n=z&g=9591", host: "kh.ssl.ak.tiles.virtualearth.net"
2021/12/02 14:50:04 [warn] 34796#17056: *1831 upstream server temporarily disabled while reading response header from upstream, client: 127.0.0.1, server: kh.ssl.ak.tiles.virtualearth.net, request: "GET /tiles/akh3112231302310113.jpeg?n=z&g=9591 HTTP/1.1", upstream: "http://127.0.0.1:39871/tiles/akh3112231302310113.jpeg?n=z&g=9591", host: "kh.ssl.ak.tiles.virtualearth.net"
2021/12/02 14:50:04 [error] 34796#17056: *1831 no live upstreams while connecting to upstream, client: 127.0.0.1, server: kh.ssl.ak.tiles.virtualearth.net, request: "GET /tiles/akh3112231302310113.jpeg?n=z&g=9591 HTTP/1.1", upstream: "http://localhost/tiles/akh3112231302310113.jpeg?n=z&g=9591", host: "kh.ssl.ak.tiles.virtualearth.net"

**Comment by derekhe** [comment]
Thanks, I will have a look.

**Comment by lazerwolf22** [comment]
It's still working fantastic! I flew for several hours last night! Thank you again!

**Comment by tarukuu** [comment]
New released Thank you.
I test flight and got data.
https://drive.google.com/drive/folders/11GgC52RmIAZkLZyf_nWF1AT6lMKBnRE9?usp=sharing

**Comment by derekhe** [comment]
@tarukuu what's your problem?
