### ISSUE TITLE
Open Question - Mayor Difficulties things that often happen to users

### ISSUE THREAD

**Issue by RBSkyofficial** [derekhe/msfs2020-google-map#156]
First, We Extremely Appreciate Derekhee for creating such Fantastic Google Maps Mods MSFS for Us,
for new and experienced user, maybe we can share something in here,
Lets begin with question :

1. Start Run.Bat with administrator = Activate before or after open the MSFS  game ? Because sometime people said before, some said after..confuse here. What is the effect if we open run.bat after the game finish loading?
2. People got stuck in loading screen 50% (in first loading ) while can play well before. if certificate pop up and we press yes, we can play else, we have to restart. How to solve this ?
3. Which server is better or faster khms or mt ?
4. nvidia gpu, dont update new driver, not compatible yet.

Thnx a lot..
no 1 - 2 -3 , maybe can share an answer here

**Comment by derekhe** [comment]
1. The mod should be opened before the MSFS2020 to override the hosts correctly. What I see is that if I start MSFS2020 first and then start the mod,  khstorelive.azureedge.net will not override to the local server. This will cause issue like the original coverage maps will active (which means you may see some auto generated tiles in some area that no bing map coverage). Also color correction overlay will active, and you will see bing map. Why people start this mod after MSFS2020 is because they have issue enter main menu of MSFS2020, which I can't reproduce on my side and can't find out why.
2. Yes, I think the certificate pop up is the root cause of 50% hang. I had once pop up and it never show up again.
3. khms server is the same server as maps.google.com while mt I guess is old server. But both of them provide same images.
4. Hmm, I have no idea, I have 496.49 with 3070 and it works good.
