### ISSUE TITLE
Stuck at 'health check passed'

### ISSUE THREAD

**Issue by whityini** [derekhe/msfs2020-google-map#73]
I am also stuck at 'health check passed', running latest version, rolling cache off.
Thank you.

**Comment by derekhe** [comment]
Please have a look the video to check if something wrong: https://youtu.be/Lk7GK5XLTt8
Or search "msfs 2020 google maps" in youtube to find out installation and usage tips.
And also give me screenshots
Please note if a pop window saying "SSL error", please click "Yes" to it.

**Comment by whityini** [comment]
I have installed the mod following youtube video as you suggested.
Yes I have a couple of security pop windows and I clicked yes to both

Here is the screenshot of my desktop
![Immagine 2021-11-13 085854](https://user-images.githubusercontent.com/94199543/141611092-6581bb6f-5e5b-4ab8-b9ac-55fd5cd98c41.jpg)
.

**Comment by derekhe** [comment]
You can run the mod when you are in MSFS2020's main menu.
Which MSFS2020 version are you using?

**Comment by whityini** [comment]
Even if I run the mod in MSFS's main menu the result is the same
![Immagine 2021-11-13 165147](https://user-images.githubusercontent.com/94199543/141650378-eabd283f-8290-4ce6-80f3-784b848f3ca5.jpg)
my version is 1.20.6.0 cracked.

**Comment by derekhe** [comment]
cracked version not supported, too old



---Original---
From: ***@***.***&gt;
Date: Sat, Nov 13, 2021 23:55 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [derekhe/msfs2020-google-map] Stuck at 'health check passed' (Issue #73)




 
Even if I run the mod in MSFS's main menu the result is the same
 
 my version is 1.20.6.0 cracked.
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by whityini** [comment]
ok thanks

**Comment by lordmonish** [comment]
hey @whityini ,it just broke my heart after knowing that it won't work with the cracked version lol.
