### ISSUE TITLE
如果使用透明代理，控制台显示会一直停留在 * Running on https://192.168.50.23:443/ (Press CTRL+C to quit)吗？

### ISSUE THREAD

**Issue by sad546879** [derekhe/msfs2020-google-map#9]
![WK%Y9U U H VEYI MZ(} IJ](https://user-images.githubusercontent.com/32971912/130186445-fcbbe58e-5771-4997-9c21-5ccc77a63f28.png)
如图，在汉化群有人宣传了一下，我和另一个人使用透明代理都仅显示这个，
另一个人使用传统vpn软件，正常显示下载图片

**Comment by faker320** [comment]
我不使用代理也有类似的问题，游戏卡蓝条，程序也卡住
![image](https://user-images.githubusercontent.com/85487730/130187842-8a32a137-193e-4fad-aed3-f462e0cf1ec2.png)

**Comment by sad546879** [comment]
上面那图是我改用ssr了，所以proxy地址填的是loacl:1080

**Comment by sad546879** [comment]
> 我不使用代理也有类似的问题，游戏卡蓝条，程序也卡住
> ![image](https://user-images.githubusercontent.com/85487730/130187842-8a32a137-193e-4fad-aed3-f462e0cf1ec2.png)

我不知道为什么我都没有trace，，直接卡在图那里了，，

**Comment by sad546879** [comment]
另：询问下离线会将地图放在那里

**Comment by sihua746** [comment]
代理网址格式     http://127.0.0.1:

**Comment by sad546879** [comment]
> 代理网址格式 http://127.0.0.1:
软路由也可以这样填吗？我留空就和上面的一样

**Comment by sad546879** [comment]
> 我不使用代理也有类似的问题，游戏卡蓝条，程序也卡住
> ![image](https://user-images.githubusercontent.com/85487730/130187842-8a32a137-193e-4fad-aed3-f462e0cf1ec2.png)

群友说是hosts没设置好，试试

**Comment by derekhe** [comment]
请试试最新的1.3.0版本，解决透明代理本地会一直死循环

**Comment by derekhe** [comment]
> 另：询问下离线会将地图放在那里

离线地图会放在cache目录下，现在新版本会创建一个大文件来装这些图片，看不到内容的。

**Comment by derekhe** [comment]
> 代理网址格式 http://127.0.0.1:

后面没有端口号，是不能正常运行的。

**Comment by faker320** [comment]
试了1.3.0版本，问题依旧存在，进不去游戏，但是在地球界面可以看谷歌的卫星图

**Comment by derekhe** [comment]
请给个刚进去时候控制台的截图和配置文件

**Comment by faker320** [comment]
现在解决了，解决办法是打开rolling cache先加载一点bing地图，然后再用Google



------------------ 原始邮件 ------------------
发件人: hesicong ***@***.***&gt;
发送时间: 2021年8月21日 12:18
收件人: derekhe/msfs2020-google-map ***@***.***&gt;
抄送: faker320 ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[derekhe/msfs2020-google-map] 如果使用透明代理，控制台显示会一直停留在 * Running on https://192.168.50.23:443/ (Press CTRL+C to quit)吗？ (#9)





 
请给个刚进去时候控制台的截图和配置文件
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
